# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/xiaomi/sm6225-common/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)
ifneq ($(filter citrus fog lime spes,$(TARGET_DEVICE)),)

endif
