normal_config:
  algo_denoise_config:
    no_face_scene:
      traditional_mfnr_strength:
        # nr_strength range[0,8] motion_ratio range[1.0, +]
        iso0: [1.0,  1.2,  1.55, 6.0]
        iso1: [1.5,  2.2,  1.85, 8.0]
        iso2: [3.8,  4.2,  2.85, 12.0]
      detail_addback_weight:
        # weight range[0,1]
        iso0: [1.0,  1.2,  64,  128,  0.30,  0.30,  1.0,  1.0,  1.0,  1.0] 
        iso1: [1.8,  2.2,  64,  128,  0.28,  0.28,  1.0,  1.0,  1.0,  1.0] 
        iso2: [3.8,  4.2,  96,  128,  0.25,  0.35,  1.0,  1.0,  1.0,  1.0] 
        iso3: [7.6,  8.6, 112,  128,  0.10,  0.25,  1.0,  1.0,  1.0,  1.0] 
        iso4: [12,    17, 112,  144,  0.10,  0.25,  1.0,  1.0,  1.0,  1.0]  
        iso5: [28,    36, 128,  160,  0.10,  0.25,  1.0,  1.0,  1.0,  1.0]   
        iso6: [58,    70, 128,  160,  0.05,  0.15,  1.0,  1.0,  1.0,  1.0]  
        iso7: [112,  144, 128,  160,  0.05,  0.10,  1.0,  1.0,  1.0,  1.0]  
        iso8: [224,  256, 128,  160,  0.05,  0.10,  1.0,  1.0,  1.0,  1.0]
    
    face_scene:
      traditional_mfnr_strength:
        # nr_strength range[0,8] motion_ratio range[1.0, +]
        iso0: [1.0,  1.2,  1.65, 4.0]
        iso1: [1.5,  2.2,  1.85, 8.0]
        iso2: [3.0,  4.2,  2.85, 8.0]
      detail_addback_weight:
        # weight range[0,1]
        iso0: [1.0,  1.2,  64,  128,  0.30,  0.30,  1.0,  1.0,  1.0,  1.0] 
        iso1: [1.8,  2.2,  64,  128,  0.28,  0.28,  1.0,  1.0,  1.0,  1.0] 
        iso2: [3.8,  6.2,  96,  128,  0.25,  0.35,  1.0,  1.0,  1.0,  1.0] 
        iso3: [7.6,  8.6, 112,  128,  0.20,  0.20,  1.0,  1.0,  1.0,  1.0] 
        iso4: [12,    17, 112,  144,  0.20,  0.20,  1.0,  1.0,  1.0,  1.0]  
        iso5: [28,    36, 128,  160,  0.10,  0.20,  1.0,  1.0,  1.0,  1.0]   
        iso6: [58,    70, 128,  160,  0.05,  0.15,  1.0,  1.0,  1.0,  1.0]  
        iso7: [112,  144, 128,  160,  0.05,  0.10,  1.0,  1.0,  1.0,  1.0]  
        iso8: [224,  256, 128,  160,  0.05,  0.10,  1.0,  1.0,  1.0,  1.0] 
    
    dump_luma_weight_map: false
    dump_motion_weight_map: false
    
  algo_sharpen_config:
    g_sharpen:
      enabled: true
      ishalocontrol: true
      islocaloshoot: true
      islocalushoot: true
      E_str_min: 1.0
      E_str_max: 64.0
      T_str_min: 0.0
      T_str_max: 256.0
      ct_thre: 4.0
      delta_min: 0.5
      e_wgt: 
      [1.0,  1.0,  1.0,  1.0,
      1.0,  1.0,  1.0,  1.0,  
      1.0,  1.0,  1.0,  1.0,   
      1.0,  1.0,  1.0,  1.0,   
      0.92, 0.84, 0.76, 0.68,    
      0.6,  0.52, 0.44, 0.36,    
      0.28, 0.2,  0.12, 0.1,   
      0.1,  0.1,  0.1,  0.1]
      t_wgt: 
      [0.0, 0.0, 0.10, 0.15,  
      0.2,  0.3,  0.4,  0.6,  
      0.8,  0.9,  1.0,  1.0,    
      1.0,  1.0,  1.0,  1.0,   
      1.0,  1.0,  1.0,  1.0,   
      1.0,  1.0,  1.0,  1.0,   
      1.0,  1.0,  1.0,  1.0,  
      1.0,  1.0,  1.0,  1.0]
      amount_edge: 1.0
      amount_detail: 1.2
      E_control_min: 0.1
      oshoot: 0.6
      ushoot: 0.6
      portrait_wgt: 0.0
      radial_anchor: [1.0, 1.0, 1.0, 1.0, 1.0]
  
lowlight_config:

