offline_config:
  offline_input_dir: '/sdcard/raw-nightcases'
  offline_output_dir: '/sdcard/raw-nightcases-Output'
Wide:
  SN:
    DeghostEv0Args:
      weight_correction_factor:
        - [200.0, 8.0]
        - [360.0, 8.0]
        - [370.0, 12.0]
      deghost_ev0_val_bias:
        - [200.0, 12.0]
        - [370.0, 10.0]
      deghost_ev0_wit_bias:
        - [200.0, 0.1]
        - [360.0, 0.1]
        - [370.0, 0.05]
        - [430.0, 0.01]
    EdgeSharpArgs:
      enabled: true
      amount: 2.0
    BackFillNoiseArgs:
      ev0_back_fill_noise_enabled: true
      merge_back_fill_noise_enabled: true
      fill_gaussian_noise_enabled: true
      back_fill_noise_scales:
        - [0.0, 0.15]
        - [20.0, 0.11]
        - [40.0, 0.09]
        - [50.0, 0.08]
        - [100.0, 0.06]
        - [180.0, 0.035]
        - [256.0, 0.025]
        - [330.0, 0.015]
      fill_gaussian_noise_scales:
        - [0.0, 0.20]
        - [20.0, 0.18]
        - [40.0, 0.16]
        - [50.0, 0.15]
        - [100.0, 0.15]
        - [180.0, 0.15]
        - [256.0, 0.15]
        - [330.0, 0.15]
      merge_back_fill_noise_scales:
        - [0.0, 0.25]
        - [20.0, 0.22]
        - [40.0, 0.18]
        - [50.0, 0.16]
        - [100.0, 0.12]
        - [180.0, 0.07]
        - [256.0, 0.05]
        - [330.0, 0.03]
    MergeArgs:
      merge_mean:
        - [200.0, 120]
        - [250.0, 110]
        - [300.0, 105]
      tar_sensitivity:
        - [275.0, 0.350000000]
        - [320.0, 0.350000000]
        - [330.0, 0.450000000]
        - [350.0, 0.700000000]
        - [370.0, 0.900000000]
        - [400.0, 3.000000000]
        - [450.0, 3.000000000]
      face_s_mean_ratios:
        - [110.0, 0.30]
        - [150.0, 0.30]
        - [170.0, 0.30]
        - [200.0, 0.15]
        - [220.0, 0.10]
    BrightenArgs:
      dark_proportion_thre:
        - [25.0, 0.10]
        - [180.0, 0.11]
        - [280.0, 0.11]
        - [330.0, 0.13]
      dark_val_thres:
        - [86.0, 48.0]
        - [280.0, 48.0]
        - [350.0, 48.0]
        - [400.0, 40.0]
        - [450.0, 35.0]
        - [520.0, 30.0]
    Ev6Args:
      face_ev6_ratios:
        - [25.0, 5.0]
        - [70.0, 4.0]
        - [85.0, 3.0]
        - [100.0, 2.1]
        - [110.0, 1.9]
        - [120.0, 1.7]
        - [150.0, 1.7]
        - [180.0, 1.0]
      backlit_face_ev6_ratios:
        - [25.0, 2.5]
        - [70.0, 2.0]
        - [85.0, 1.5]
        - [100.0, 1.2]
        - [110.0, 1.05]
        - [120.0, 1.0]
        - [140.0, 1.2]
        - [150.0, 1.4]
        - [165.0, 1.2]
        - [180.0, 1.0]
      face_ev6_limits:
        - [200.0, 2.5, 5.5]
        - [300.0, 1.5, 4.3]
        - [350.0, 1.3, 3.8]
        - [380.0, 1.2, 3.8]
        - [400.0, 1.0, 3.0]
        - [470.0, 1.0, 2.0]
        - [500.0, 1.0, 1.6]
      noface_ev6_limits:
        - [86.0, 3.0, 5.8]
        - [180.0, 2.7, 5.8]
        - [250.0, 2.6, 5.4]
        - [280.0, 2.3, 5.2]
        - [330.0, 1.9, 3.8]
        - [400.0, 1.5, 3.8]
        - [420.0, 1.0, 1.5]
        - [480.0, 1.0, 1.0]
        - [500.0, 1.0, 1.0]
    SkyDarkenArgs:
      face_sky_use_ev: 2
      noface_sky_use_ev: 1
      face_sky_ratio:
        - [25.0, 0.3]
        - [180.0, 0.3]
      noface_sky_ratio:
        - [25.0, 0.4]
        - [180.0, 0.4]
        - [400.0, 0.4]
        - [420.0, 0.1]
        - [450.0, 0.1]
  SE:
    DeghostEv0Args:
      weight_correction_factor:
        - [200.0, 8.0]
        - [360.0, 8.0]
        - [370.0, 12.0]
      deghost_ev0_val_bias:
        - [200.0, 12.0]
        - [370.0, 10.0]
      deghost_ev0_wit_bias:
        - [200.0, 0.1]
        - [360.0, 0.1]
        - [370.0, 0.05]
        - [430.0, 0.01]
    EdgeSharpArgs:
      enabled: true
      amount: 10.0
    BackFillNoiseArgs:
      ev0_back_fill_noise_enabled: true
      merge_back_fill_noise_enabled: true
      fill_gaussian_noise_enabled: true
      back_fill_noise_scales:
        - [0.0, 0.25]
        - [20.0, 0.20]
        - [40.0, 0.18]
        - [50.0, 0.08]
        - [100.0, 0.06]
        - [180.0, 0.035]
        - [256.0, 0.025]
        - [330.0, 0.015]
      fill_gaussian_noise_scales:
        - [0.0, 0.20]
        - [20.0, 0.18]
        - [40.0, 0.16]
        - [50.0, 0.15]
        - [100.0, 0.15]
        - [180.0, 0.15]
        - [256.0, 0.15]
        - [330.0, 0.15]
      merge_back_fill_noise_scales:
        - [0.0, 0.25]
        - [20.0, 0.22]
        - [40.0, 0.18]
        - [50.0, 0.16]
        - [100.0, 0.12]
        - [180.0, 0.07]
        - [256.0, 0.05]
        - [330.0, 0.03]
    MergeArgs:
      merge_mean:
        - [200.0, 120]
        - [250.0, 110]
        - [300.0, 105]
      tar_sensitivity:
        - [275.0, 0.350000000]
        - [320.0, 0.350000000]
        - [330.0, 0.450000000]
        - [350.0, 0.700000000]
        - [370.0, 0.900000000]
        - [400.0, 3.000000000]
        - [450.0, 3.000000000]
      face_s_mean_ratios:
        - [110.0, 0.30]
        - [150.0, 0.30]
        - [170.0, 0.30]
        - [200.0, 0.15]
        - [220.0, 0.10]
    BrightenArgs:
      dark_proportion_thre:
        - [25.0, 0.10]
        - [180.0, 0.11]
        - [280.0, 0.11]
        - [330.0, 0.13]
      dark_val_thres:
        - [86.0, 48.0]
        - [280.0, 48.0]
        - [350.0, 48.0]
        - [400.0, 40.0]
        - [450.0, 35.0]
        - [520.0, 30.0]
    Ev6Args:
      face_ev6_ratios:
        - [25.0, 5.0]
        - [70.0, 4.0]
        - [85.0, 3.0]
        - [100.0, 2.1]
        - [110.0, 1.9]
        - [120.0, 1.7]
        - [150.0, 1.7]
        - [180.0, 1.0]
      backlit_face_ev6_ratios:
        - [25.0, 2.5]
        - [70.0, 2.0]
        - [85.0, 1.5]
        - [100.0, 1.2]
        - [110.0, 1.05]
        - [120.0, 1.0]
        - [140.0, 1.2]
        - [150.0, 1.4]
        - [165.0, 1.2]
        - [180.0, 1.0]
      face_ev6_limits:
        - [200.0, 2.5, 5.5]
        - [300.0, 1.5, 4.3]
        - [350.0, 1.3, 3.8]
        - [380.0, 1.2, 3.8]
        - [400.0, 1.0, 3.0]
        - [470.0, 1.0, 2.0]
        - [500.0, 1.0, 1.6]
      noface_ev6_limits:
        - [86.0, 3.0, 5.8]
        - [180.0, 2.7, 5.8]
        - [250.0, 2.6, 5.4]
        - [280.0, 2.3, 5.2]
        - [330.0, 1.9, 3.8]
        - [400.0, 1.5, 3.8]
        - [420.0, 1.0, 1.5]
        - [480.0, 1.0, 1.0]
        - [500.0, 1.0, 1.0]
    SkyDarkenArgs:
      face_sky_use_ev: 2
      noface_sky_use_ev: 1
      face_sky_ratio:
        - [25.0, 0.3]
        - [180.0, 0.3]
      noface_sky_ratio:
        - [25.0, 0.4]
        - [180.0, 0.4]
        - [400.0, 0.4]
        - [420.0, 0.1]
        - [450.0, 0.1]
Ultra_Wide:
  SN:
    DeghostEv0Args:
      weight_correction_factor:
        - [200.0, 4.0]
        - [360.0, 4.0]
        - [460.0, 6.0]
      deghost_ev0_val_bias:
        - [200.0, 12.0]
        - [370.0, 12.0]
        - [460.0, 10.0]
      deghost_ev0_wit_bias:
        - [200.0, 0.1]
        - [360.0, 0.1]
        - [460.0, 0.05]
    EdgeSharpArgs:
      enabled: true
      amount: 7.0
    BackFillNoiseArgs:
      ev0_back_fill_noise_enabled: true
      merge_back_fill_noise_enabled: false
      fill_gaussian_noise_enabled: true
      back_fill_noise_scales:
        - [0.0, 0.25]
        - [30.0, 0.22]
        - [60.0, 0.18]
        - [100.0, 0.10]
        - [180.0, 0.06]
        - [256.0, 0.03]
      fill_gaussian_noise_scales:
        - [0.0, 0.20]
        - [20.0, 0.18]
        - [40.0, 0.16]
        - [50.0, 0.15]
        - [100.0, 0.15]
        - [180.0, 0.15]
        - [256.0, 0.15]
        - [330.0, 0.15]
      merge_back_fill_noise_scales:
        - [0.0, 0.25]
        - [20.0, 0.22]
        - [40.0, 0.18]
        - [50.0, 0.16]
        - [100.0, 0.12]
        - [180.0, 0.07]
        - [256.0, 0.05]
        - [330.0, 0.03]
    MergeArgs:
      merge_mean:
        - [200.0, 120]
        - [320.0, 120]
      tar_sensitivity:
        - [270.0, 0.200000000]
        - [320.0, 0.550000000]
        - [350.0, 0.700000000]
        - [370.0, 0.900000000]
        - [400.0, 3.000000000]
        - [450.0, 3.000000000]
      face_s_mean_ratios:
        - [20.0, 0.05]
        - [80.0, 0.05]
        - [100.0, 0.02]
        - [125.0, 0.01]
    BrightenArgs:
      dark_proportion_thre:
        - [25.0, 0.15]
        - [180.0, 0.15]
      dark_val_thres:
        - [86.0, 48.0]
        - [450.0, 48.0]
        - [520.0, 48.0]
    Ev6Args:
      face_ev6_ratios:
        - [25.0, 5.0]
        - [70.0, 4.5]
        - [100.0, 3.5]
        - [125.0, 1.8]
        - [180.0, 1.0]
      backlit_face_ev6_ratios:
        - [25.0, 2.5]
        - [70.0, 2.25]
        - [100.0, 1.8]
        - [125.0, 1.05]
        - [180.0, 1.0]
      face_ev6_limits:
        - [200.0, 2.0, 6.0]
        - [300.0, 2.0, 5.0]
        - [400.0, 1.5, 3.0]
        - [470.0, 1.0, 2.0]
      noface_ev6_limits:
        - [78.0, 2.0, 6.0]
        - [250.0, 1.0, 3.5]
        - [330.0, 1.0, 2.3]
        - [380.0, 1.0, 1.5]
        - [470.0, 1.0, 1.3]
    SkyDarkenArgs:
      face_sky_use_ev: 2
      noface_sky_use_ev: 1
      face_sky_ratio:
        - [25.0, 0.3]
        - [180.0, 0.3]
      noface_sky_ratio:
        - [25.0, 0.4]
        - [180.0, 0.4]
  SE:
    DeghostEv0Args:
      weight_correction_factor:
        - [200.0, 4.0]
        - [360.0, 4.0]
        - [460.0, 6.0]
      deghost_ev0_val_bias:
        - [200.0, 12.0]
        - [370.0, 12.0]
        - [460.0, 10.0]
      deghost_ev0_wit_bias:
        - [200.0, 0.1]
        - [360.0, 0.1]
        - [460.0, 0.05]
    EdgeSharpArgs:
      enabled: true
      amount: 3.0
    BackFillNoiseArgs:
      ev0_back_fill_noise_enabled: true
      merge_back_fill_noise_enabled: false
      fill_gaussian_noise_enabled: true
      back_fill_noise_scales:
        - [0.0, 0.20]
        - [30.0, 0.19]
        - [60.0, 0.18]
        - [100.0, 0.10]
        - [180.0, 0.06]
        - [256.0, 0.03]
      fill_gaussian_noise_scales:
        - [0.0, 0.20]
        - [20.0, 0.18]
        - [40.0, 0.16]
        - [50.0, 0.15]
        - [100.0, 0.15]
        - [180.0, 0.15]
        - [256.0, 0.15]
        - [330.0, 0.15]
      merge_back_fill_noise_scales:
        - [0.0, 0.25]
        - [20.0, 0.22]
        - [40.0, 0.18]
        - [50.0, 0.16]
        - [100.0, 0.12]
        - [180.0, 0.07]
        - [256.0, 0.05]
        - [330.0, 0.03]
    MergeArgs:
      merge_mean:
        - [200.0, 110]
        - [320.0, 110]
      tar_sensitivity:
        - [270.0, 0.200000000]
        - [320.0, 0.550000000]
        - [350.0, 0.700000000]
        - [370.0, 0.900000000]
        - [400.0, 3.000000000]
        - [450.0, 3.000000000]
      face_s_mean_ratios:
        - [20.0, 0.05]
        - [80.0, 0.05]
        - [100.0, 0.02]
        - [125.0, 0.01]
    BrightenArgs:
      dark_proportion_thre:
        - [25.0, 0.15]
        - [180.0, 0.15]
      dark_val_thres:
        - [86.0, 48.0]
        - [450.0, 48.0]
        - [520.0, 48.0]
    Ev6Args:
      face_ev6_ratios:
        - [25.0, 5.0]
        - [70.0, 4.5]
        - [100.0, 3.5]
        - [125.0, 1.8]
        - [180.0, 1.0]
      backlit_face_ev6_ratios:
        - [25.0, 2.5]
        - [70.0, 2.25]
        - [100.0, 1.8]
        - [125.0, 1.05]
        - [180.0, 1.0]
      face_ev6_limits:
        - [200.0, 2.0, 6.0]
        - [300.0, 2.0, 5.0]
        - [400.0, 1.5, 3.0]
        - [470.0, 1.5, 2.0]
      noface_ev6_limits:
        - [78.0, 1.0, 5.0]
        - [250.0, 1.0, 3.5]
        - [330.0, 1.0, 2.3]
        - [380.0, 1.0, 1.5]
        - [470.0, 1.0, 1.3]
    SkyDarkenArgs:
      face_sky_use_ev: 2
      noface_sky_use_ev: 1
      face_sky_ratio:
        - [25.0, 0.3]
        - [180.0, 0.3]
      noface_sky_ratio:
        - [25.0, 0.4]
        - [180.0, 0.4]
