# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/xiaomi/sm6150-common/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifneq ($(filter **** FILL IN ALL DEVICE NAMES, SPACE DELIMITED ****,$(TARGET_DEVICE)),)

endif
