# push to /vendor/etc/camera to be read by main program
# version: 2022_1017_2012_M2_S_R
algo_params:
  common:
    daylight_lux_thres: 275
    use_faceblur: false
  align:
  deghost:
  merge:

  denoise:
    dldenoise_lux_thres: 250
    dldenoise_iso_thres: 230

    m_min_front_dlw: 0.2
    m_max_front_dlw: 0.4
    m_min_back_dlw: 0.4
    m_max_back_dlw: 0.7
    nlm_window_size: 7
    nlm_template_size: 3

  post_process:
    face_light: 0
    face_contrast: 0
    face_gamma: 0.0
    bg_light_ratio: 0.5

    # sharp
    portrait_sharp_0: 1.2 # 2.0
    portrait_sharp_1: 1.0 # 1.6
    portrait_sharp_2: 0.8 # 1.2
    portrait_sharp_3: 0.6 # 1.2

    #satuation
    adjust_satuation: false
    satuation_a: 0.0
    satuation_b: 0.0

    #thres
    blend_sharpen_lux_thres: 400

    dark_bg_light_ratio: 0.0
    dark_lighten_lux_thresh: 600.0


