# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/xiaomi/trinket-common/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifneq ($(filter ginkgo laurel_sprout,$(TARGET_DEVICE)),)

endif
