# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/xiaomi/sm8550-common/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifneq ($(filter fuxi nuwa ishtar vermeer,$(TARGET_DEVICE)),)

endif
